# Generated by Django 4.1.2 on 2022-10-20 17:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_pic', models.URLField(max_length=300)),
                ('short_bio', models.CharField(blank=True, max_length=300)),
                ('long_bio', models.CharField(blank=True, max_length=400, null=True)),
                ('advocate_years_exp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Social_Data',
            fields=[
                ('sdid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube', models.URLField(blank=True, max_length=300, null=True)),
                ('twitter', models.URLField(blank=True, max_length=300, null=True)),
                ('github', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(max_length=300)),
                ('summary', models.CharField(default='', max_length=400)),
                ('href', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('advocates', models.ManyToManyField(blank=True, default='', related_name='advocates', to='core.advocate')),
            ],
        ),
        migrations.AddField(
            model_name='advocate',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company'),
        ),
        migrations.AddField(
            model_name='advocate',
            name='links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.social_data'),
        ),
    ]
