# Generated by Django 4.1.2 on 2022-10-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='href',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
