# Generated by Django 4.1.2 on 2022-10-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='advocate_years_exp',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='links',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='long_bio',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='short_bio',
        ),
        migrations.AddField(
            model_name='advocate',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='advocate',
            name='twitter',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='advocate',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Social_Data',
        ),
    ]
