# Generated by Django 4.1.2 on 2022-10-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_advocate_profile_pic_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_data',
            name='github',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='social_data',
            name='twitter',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='social_data',
            name='youtube',
            field=models.URLField(max_length=300),
        ),
    ]
